services:
  app:
    container_name: bit
    build: .
    environment:
      ENV: production
      ADMIN_NAME: ${ADMIN_NAME:-Admin}
      ADMIN_API_KEY: ${ADMIN_API_KEY:?ADMIN_API_KEY must be set}
    ports:
      - 4000:4000
    volumes:
      - sqlite_data:/usr/src/app/sqlite

volumes:
  sqlite_data:
