services:
  app:
    container_name: bit
    build: .
    environment:
      ENV: production
      ADMIN_NAME: 'Tester'
      ADMIN_API_KEY: '0p+mDvbpZGLPGVCXnV+EDduR9Blkv27Dhq9XSzSbdQY='
    ports:
      - 4000:4000
    volumes:
      - sqlite_data:/app/sqlite

volumes:
  sqlite_data:
