version: '3'

services:
  db:
    image: postgres:12.5-alpine
    volumes:
      - test_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_12345
      POSTGRES_DB: test_url_shortener
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - gem_cache:/usr/local/bundle/gems
    command: bundle exec rails test
    environment:
       RAILS_ENV: test
       HOSTNAME: 0.0.0.0
       PORT: 3000
       DATABASE_URL: postgres://user:user_12345@db:5432/test_url_shortener
    depends_on:
      - db
volumes:
  gem_cache:
  test_db_data: