name: Deploy production to donado.co
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: RuboCop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.3.0
        with:
          action_config_path: .github/config/rubocop_linter_action.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@ssh.donado.co:22/url-shortener"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
